"""
update_projects.py - Automatically syncs all .json drawings in projects/ into user_projects.js
Run this script whenever you drop a new saved drawing into the projects/ directory.
"""

import os
import json
import glob
import re

PROJECTS_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(PROJECTS_DIR)

def main():
    json_files = glob.glob(os.path.join(PROJECTS_DIR, "*.json"))
    if not json_files:
        print("No .json project files found in projects/")
        return

    projects_map = {}
    options_html = []

    for fpath in json_files:
        fname = os.path.basename(fpath)
        base_id = os.path.splitext(fname)[0]
        try:
            with open(fpath, "r", encoding="utf-8") as f:
                data = json.load(f)

            # Determine human readable title
            room_count = len(data.get("rooms", []))
            plot = data.get("plot", {})
            v = plot.get("vertices", [])
            if v:
                xs = [p["x"] for p in v]
                ys = [p["y"] for p in v]
                w_ft = round((max(xs) - min(xs)) / 12)
                h_ft = round((max(ys) - min(ys)) / 12)
                dims_str = f"{w_ft}' × {h_ft}'"
            else:
                dims_str = "Custom"

            title = f"{dims_str} Residence ({room_count} Rooms)"
            if "pooja" in json.dumps(data).lower():
                title += " - Pooja & Store"

            projects_map[base_id] = data
            options_html.append(f'                        <option value="{base_id}">★ {title}</option>')
            print(f"Loaded: {fname} -> {title}")
        except Exception as e:
            print(f"Error reading {fname}: {e}")

    # 1. Write user_projects.js
    js_content = "/**\n * user_projects.js - Auto-generated by update_projects.py\n */\n\n"
    js_content += "export const USER_SAVED_PROJECTS = " + json.dumps(projects_map, indent=2) + ";\n"

    user_projects_js = os.path.join(PROJECTS_DIR, "user_projects.js")
    with open(user_projects_js, "w", encoding="utf-8") as f:
        f.write(js_content)
    print(f"Updated {user_projects_js}")

    # 2. Update index.html optgroup
    index_html_path = os.path.join(ROOT_DIR, "index.html")
    if os.path.exists(index_html_path):
        with open(index_html_path, "r", encoding="utf-8") as f:
            html = f.read()

        new_optgroup = '<optgroup label="📁 My Saved Projects">\n' + "\n".join(options_html) + "\n                    </optgroup>"
        updated_html = re.sub(
            r'<optgroup label="📁 My Saved Projects">[\s\S]*?</optgroup>',
            new_optgroup,
            html
        )

        with open(index_html_path, "w", encoding="utf-8") as f:
            f.write(updated_html)
        print(f"Updated {index_html_path} dropdown options.")

    print("\nAll projects synced successfully! You can now run 'git add . && git commit -m \"add drawing\" && git push'.")

if __name__ == "__main__":
    main()
